#Service id
spring.application.name=notification-service

#Server Port
server.port=8087

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Link MS with config server
spring.config.import=optional:configserver:

#logging properties
logging.level.root=INFO
logging.level.com.japes.notificationservice=DEBUG

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true