#Service id(Application name)
spring.application.name=api-gateway

#Server Port
server.port=8080

#Link MS with config server
spring.config.import=optional:configserver:

#logging properties
logging.level.root=INFO
logging.level.com.japes.inventoryservice=DEBUG