#Service id(Application name)
spring.application.name=api-gateway

#Server Port
server.port=8080

#Link MS with config server
spring.config.import=optional:configserver:

#logging properties
logging.level.root=INFO
logging.level.com.japes.inventoryservice=DEBUG

#Gateway Routes
#User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/users/**

#Product Service
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/products/**,/api/v1/categories/**,/api/v1/product-variants/**