#Service id(Application name)
spring.application.name=payment-service

#Server port
server.port=8084

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Link MS with config server
spring.config.import=optional:configserver:

# Datasource configurations
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db

# Razorpay
razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET}

#logging properties
logging.level.root=INFO
logging.level.com.japes.paymentservice=DEBUG
logging.file.name=logs/payment-service.log