#Service id(Application name)
spring.application.name=user-service

#Server port
server.port=8085

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Link MS with config server
spring.config.import=optional:configserver:

# Datasource configurations
spring.datasource.url=jdbc:mysql://localhost:3306/user_db

#JWT
jwt.secret = ${JWT_SECRET}
jwt.expiration = 3600000

#logging properties
logging.level.root=INFO
logging.level.com.japes.userservice=DEBUG
logging.file.name=logs/user-service.log