#Service id(Application name)
spring.application.name=order-service

#Server Port
server.port=8083

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Link MS with config server
spring.config.import=optional:configserver:

# Datasource configurations
spring.datasource.url=jdbc:mysql://localhost:3306/order_db

#logging properties
logging.level.root=INFO
logging.level.com.japes.orderservice=DEBUG
#logging.file.name=logs/order-service.log