#Service id(Application name)
spring.application.name=order-service

#Server Port
server.port=8083

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Register with eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Enable health actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Register using IP address
eureka.instance.prefer-ip-address=true

# Datasource configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=manager21
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Jpa hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#logging properties
logging.level.root=INFO
logging.level.com.japes.productservice=DEBUG
logging.file.name=logs/order-service.log