spring.application.name=discovery-server

#Eureka Server Port
server.port=8761

#Make this project as eureka discovery server by disabling registry and fetch operations
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#logging properties
logging.level.root=INFO
logging.level.com.japes.discoveryserver=DEBUG
logging.file.name=logs/discovery-server.log 

#Enable health actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always