# Service id(Application name)
spring.application.name=product-service

#Server Port
server.port=8081

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Link MS with config server
spring.config.import=optional:configserver:

# Datasource configurations
spring.datasource.url=jdbc:mysql://localhost:3306/product_db

#logging properties
logging.level.root=INFO
logging.level.com.japes.productservice=DEBUG
logging.file.name=logs/product-service.log