#Service id(Application name)
spring.application.name=inventory-service

#Server Port
server.port=8082

#Instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Link MS with config server
spring.config.import=optional:configserver:

# Datasource configurations
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db

#logging properties
logging.level.root=INFO
logging.level.com.japes.inventoryservice=DEBUG
#logging.file.name=logs/inventory-service.log

spring.kafka.consumer.group-id=inventory-service-v3
spring.kafka.consumer.auto-offset-reset=latest

#spring.kafka.consumer.properties.spring.json.value.default.type=com.japes.inventoryservice.event.OrderCreatedEvent
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.japes.inventoryservice.event